# Site settings
title: Owen Arden
email: owen@soe.ucsc.edu
description: Owen Arden's Academic Home Page
baseurl: "/home" # the subpath of your site, e.g. /blog/
url: "https://owenarden.github.io" # the base hostname & protocol for your site

# Google analytics ID: Remove or use your own!
# google_analytics: UA-167467135-1
# google_analytics_4: G-02KDGRRB2T
# google_tag_manager: GTM-TZ9Z7HZ

# Footer info
affiliation: >
    Prof. Owen Arden<br/>
    Assistant Professor<br/>
    <a href="https://engineering.ucsc.edu/departments/computer-science-and-engineering" target="_blank">Computer Science and Engineering</a><br/>
    UC Santa Cruz

location: >
  <a href="https://engineering.ucsc.edu/about/locations/baskin-engineering-building" target="_blank">Engineering 2</a><br/>
  UC Santa Cruz<br/>
  MS: SOE3<br/>
  1156 High Street<br/>
  Santa Cruz, CA 95062

contact: >
    <a href="mailto:owen@soe.ucsc.edu" target="_blank"><i class="fa fa-envelope fa-1x"></i> Contact Owen via email</a> <br/>

# Pages shown in navbar
nav_pages:
  - name: about
  - name: publications
#  - name: talks
#  - name: research
#  - name: software
# - name: team
  - name: teaching

include:
  - .htaccess
  - _pages

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links

plugins: ['jekyll/scholar']

scholar:

  last_name: Arden
  first_name: [Owen]

  style: shb
  locale: en

  source: /cv/
  bibliography: arden.bib
  bibliography_template: bibtemplate
  sort_by: year, month
  order: descending

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

  bibliography_list_attributes:
    reversed: "reversed"

exclude:
  - Gemfile
  - Gemfile.lock
  - update_boostrap.sh
  - switch_theme.sh
  - tags
  - Rakefile
